export const REQUEST_FOOD = "REQUEST_FOOD";
export const FETCH_FOOD = "FETCH_FOOD";
export const RECEIVE_FOOD = "RECEIVE_FOOD";

export const CREATE_FOOD = "CREATE_FOOD";
export const UPDATE_FOOD = "UPDATE_FOOD";
export const DELETE_FOOD = "DELETE_FOOD";

export const REQUEST_BODYWEIGHT = "REQUEST_BODYWEIGHT";
export const FETCH_BODYWEIGHT = "FETCH_BODYWEIGHT";
export const RECEIVE_BODYWEIGHT = "RECEIVE_BODYWEIGHT";

export const CREATE_BODYWEIGHT = "CREATE_BODYWEIGHT";
export const DELETE_BODYWEIGHT = "DELETE_BODYWEIGHT";

export const REQUEST_USER_PROFILE = "REQUEST_USER_PROFILE";
export const RECEIVE_USER_PROFILE = "RECEIVE_USER_PROFILE";
